apiVersion: v1
data:
  NEXUS_PASSWORD: bmVsaG9zbmk=
  NEXUS_REPO: aHR0cHM6Ly9uZXh1cy1zYXAtY29tbWVyY2UuMTkyLjE2OC45OS4xMDIubmlwLmlvL3JlcG9zaXRvcnkvbmVsaG9zbmkv
  NEXUS_URL: aHR0cHM6Ly9uZXh1cy1zYXAtY29tbWVyY2UuMTkyLjE2OC45OS4xMDIubmlwLmlv
  NEXUS_USER: bmVsaG9zbmk=
kind: Secret
metadata:
  name: nexus-secret
type: Opaque
