apiVersion: v1
kind: Template
labels:
  template: hybris-app
metadata:
  annotations:
    description: Builds a SAP Commerce application
    iconClass: icon-tomcat
    tags: java,tomcat,hybris
  name: hybris-app
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 9001-tcp
      port: 9001
      protocol: TCP
      targetPort: 9001
    - name: 9002-tcp
      port: 9002
      protocol: TCP
      targetPort: 9002
    selector:
      application: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      application: ${APPLICATION_NAME}
  spec:
    host:
    port:
      targetPort: 9002-tcp
    tls:
      termination: passthrough
    to:
      kind: Service
      name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:${APPLICATION_OUPUT_IMAGE_TAG}
    resources:
      limits:
        cpu: "${BUILD_CPU}"
        memory: "${BUILD_MEMORY}"
    source:
      contextDir: ${SOURCE_CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      sourceSecret:
        name: ${SOURCE_SECRET}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}
      type: Source
    triggers:
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      application: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
        - image: ""
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 9001
            protocol: TCP
          - containerPort: 9002
            protocol: TCP
          resources:
            limits:
              cpu: "${LIMITS_CPU}"
              memory: "${LIMITS_MEMORY}"
            requests:
              cpu: "${REQUESTS_CPU}"
              memory: "${REQUESTS_MEMORY}"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/hybris/config
            name: ${HYBRIS_CONFIG}
          - mountPath: /etc/hybris/licence
            name: ${HYBRIS_LICENSE}
            readOnly: true
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: ${HYBRIS_CONFIG}
          name: ${HYBRIS_CONFIG}
        - name: ${HYBRIS_LICENSE}
          secret:
            defaultMode: 420
            secretName: ${HYBRIS_LICENSE}
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:${APPLICATION_OUPUT_IMAGE_TAG}
      type: ImageChange
parameters:
- description: The name for the Hybris application.
  displayName: Application name
  name: APPLICATION_NAME
  required: true
  value: hybris-app
- description: Name of the Hybris Base Image
  displayName: Base image name
  name: BASE_IMAGE_NAME
  required: true
  value: hybris-base
- description: Tag of the Hybis Base Image.
  displayName: Hybris base image tag
  name: BASE_IMAGE_TAG
  required: true
  value: latest
- description: Name of the namespace containing the base Hybris image.
  displayName: Base image namespace
  name: BASE_IMAGE_NAMESPACE
  required: true
  value: latest
- name: SOURCE_REPOSITORY_URL
  displayName: Git Repository URL
  description: The URL of the repository with your application source code.
  required: true
- name: SOURCE_REPOSITORY_REF
  displayName: Git Reference
  description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default (master) branch.
- name: SOURCE_CONTEXT_DIR
  displayName: Git Context Directory
  description: Set this to the directory where the build information is (e.g. Dockerfile)
    if not using the default
- name: SOURCE_SECRET
  displayName: Source Secret
  description: Name of the source secret
  value: gogs-secret
- name: APPLICATION_OUPUT_IMAGE_TAG
  displayName: Image tag for output Hybris base.
  description: This is the image tag used for the Hybris base.
  value: latest
- description: Generic build trigger secret
  displayName: Generic Webhook Secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: GENERIC_WEBHOOK_SECRET
  required: true
- name: BUILD_CPU
  displayName: Build CPU.
  description: CPU to allocate for the build
  value: "2"
  required: true
- name: BUILD_MEMORY
  displayName: Build Memory.
  description: Amount of memory to dedicte the build
  value: 4Gi
  required: true
- name: REQUESTS_CPU
  displayName: Request CPU.
  description: Amount of CPU to request
  value: "1"
  required: true
- name: REQUESTS_MEMORY
  displayName: Request Memory.
  description: Amount of Memory to request
  value: "1Gi"
  required: true
- name: LIMITS_CPU
  displayName: Limits CPU.
  description: Amount of CPU to limit
  value: "2"
  required: true
- name: LIMITS_MEMORY
  displayName: Limits Memory.
  description: Amount of Memory to limit
  value: "6Gi"
  required: true
- name: HYBRIS_LICENSE
  displayName: Hybris License.
  description: Name of the secret containing the Hybris license
  value: "hybrislicense"
  required: true
- name: HYBRIS_CONFIG
  displayName: Hybris Config.
  description: Name of the configmap containing the server configuration
  value: "hybrisconfig"
  required: true